### ISSUE TITLE
How to share definitions across the ecosystem?

### ISSUE THREAD

**Issue by wooorm** [syntax-tree/unist-ts#1]
I’m not too familiar with the typescript-way of sharing stuff. How should we add types for mdast/hast/nlcst etc? how do they use the typings exposed here?

**Comment by wooorm** [comment]
@ChristianMurphy Oh, P.S., I fiddled with how to expose unist by trying to include it from another definition file, this is what I came up with, not sure if it’s good though:

https://github.com/syntax-tree/unist-ts/blob/ea496d1046c96667253ed9c4432993ca4d0ad935/index.d.ts#L1-L3

And, the typescript checker failed over the `type!: string` part 🤷‍♂️ so I removed it:

https://github.com/syntax-tree/unist-ts/blob/ea496d1046c96667253ed9c4432993ca4d0ad935/index.d.ts#L7

**Comment by ChristianMurphy** [comment]
:thinking: So if we are going to keep the definitions separate from the source code, I wonder if http://definitelytyped.org/ may be a good option.

**Comment by wooorm** [comment]
Well there’s no source code anyway so I’m not sure how to do it otherwise? 🤷‍♂️

**Comment by ChristianMurphy** [comment]
That is where definitely typed comes in, it is an external repo that stores typescript definitions.
There is already a somewhat outdated version of the Unist definition there https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/unist
If the definition is going to be external I'd lean toward destributing it from there, and linking to it from unist.

**Comment by wooorm** [comment]
That could work. I’m not sure type systems support dependencies that are just abstract definitions.
I feel like maintaining them here has a benefit over managing them in a huge repo. But then again I don’t use typescript 🤷‍♂️

**Comment by blakeembrey** [comment]
@wooorm You can write a definition file and include it with the library or separately. For TypeScript to automatically use the types, you just need to specify `types` in `package.json` and direct it to the `.d.ts` file. In any consuming library, you can reuse the types by importing as you may runtime code, with `import { Type } from 'unist'`. It'll use the `.d.ts` to ensure the types exist.

To export and import types, they use ES6 module syntax such as `export type Foo = string`. There's nothing wrong with providing just types in your package, but I'd avoid writing the definition as it currently is since it's considering "global" right now. It's difficult to properly manage "global" types since they can conflict and create problems. I'd be happy to take a pass at writing this as a regular module system, and you could put that in `unist` or `unist-ts` depending on your publishing preferences.

**Comment by wooorm** [comment]
I’d prefer the types to not be in the unist repo. that repo should be the spec only, and not discern itself with JavaScript (or typescript), that’s why I created this repo.

for this issue, I’m not sure how to do it, could you show me? I’d super appreciate it!

**Comment by blakeembrey** [comment]
@wooorm Sorry, was working on the `linked-list` lib first. I just checked this out and it actually looks pretty much correct as is, the only thing to do is remove the `declare namespace` wrapper`. I can submit a PR to demonstrate.

As for `export as namespace`, you'd use that if you want the "module" to be available on the global in packages that don't use a module system. Since you only use CommonJS in your packages, it probably isn't necessary.

**Comment by wooorm** [comment]
Perfect, thank you!

I think this can now be published to npm, right? One follow up question: How would this be used from other abstract type definitions (like `mdast-ts`), that are also just typings but will need this as a dependency?

**Comment by blakeembrey** [comment]
Doing NPM install and using it as is should work. Just use ES6-style imports when writing the definition. Feel free to add simple tests to validate the types.

**Comment by wooorm** [comment]
Sweet, thanks @blakeembrey!

In that case I think this issue is done!

@ChristianMurphy, would you like to publish?
